### ISSUE TITLE
List of Jokes

### ISSUE THREAD

**Issue by PReichetanz** [PReichetanz/backend-read-ffm-web-23-1#1]
## Value Proposition

- As a ...
- I want to ...
- in order to ...

## Description

- Scribble, design, or text
- Make sure you scribble "real" proportions.

## Acceptance criteria

- [x] What happens when an entry is empty?
- [x] How should something behave?
- [x] What is the text of an alert?

## Tasks

- [x] List the tasks that need to be performed within the dev team
- [x] Create branch
- [x] Write tests
- [x] Generate dummy-data
- [x] If it's the first user story: Global styles

**Comment by Gblur** [comment]
hey cool

**Comment by LuYujin9** [comment]
Ich finde , die Idee ist super!

**Comment by XxKikoxX** [comment]
Looks good

**Comment by abieber1408** [comment]
Sehr good.
